services:
  mariadb:
    image: mariadb
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      DB_ROOT_PASS: ${DB_ROOT_PASS}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}
    restart: always
    networks:
      - inception

  wordpress:
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html/
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}
      WP_DB_HOST: ${DB_HOST}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_SITE_NAME: ${WP_SITE_NAME}
      WP_SITE_URL: ${WP_SITE_URL}
    restart: always
    networks:
      - inception

  nginx:
    image: nginx
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/nrabehar/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/nrabehar/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge